### ISSUE TITLE
Loading RDF file into memory and running server from command line throws exception

### ISSUE THREAD

**Issue by jjkaelin** [galbiston/geosparql-fuseki#1]
I have jena fuseki running as a standalone server and am trying to get fuseki geosparql running. I am however getting an error when using the test file provided on github. 

Steps to reproduce my problem:
- download geosparql-fuseki-1.0.6 release 
- download geosparql_test.rdf from geosparql-jena
- run .\geosparql-fuseki.bat -rf "geosparql_test.rdf>xml

Running  ./bin/geosparql-fuseki  --help  works.

As a first test, I followed the README, loading an RDF file (XML format) into memory and running the server from a command line: 
   .\geosparql-fuseki.bat -rf "geosparql_test.rdf>xml" 
which I understand should write a default dataset ds into memory and then start the server.

For me however this throws an exception and does not start the server:
   ERROR GeoSPARQL Server:  Exiting - No Geometry Literals or Geo predicates found in
                                                    Dataset or Model.: ds

I do get a WARNING: The “SIS_DATA” environment variable is not set.
I have not yet set the SIS_DATA environment variable.

Using the test file 'test.rdf' (scraped from your github) gives the same result (and no WARNING).

Looking at the source, it is not clear to me if the exception is caused by the geometry defined in the test files ("It is expected that at least one Geometry Literal or Geo Predicate is present in a dataset.") or by the SRS (which I understand should default to WGS84). 

At this point it does not seem to me that configuring SIS would be of any help. From the REAME: "A subset of the EPSG spatial/coordinate reference systems are included by default from the Apache SIS project (http://sis.apache.org)."

Could you kindly confirm that the test data 'geosparql_test.rdf' should work with the present release? Am I perhaps missing some other essential configuration step?

I am running under Ubuntu 18.04.2 LTS.

Thanks in advance for your help.

**Comment by galbiston** [comment]
Hi,

The geosparql_test.rdf file does work with the current release. The issue is with not running the GeoSPARQL inferencing that the file needs to have the full RDF structure (when loading into a Jena TDB then this only needs to be done once). I've updated the README to make this clearer. There was some feedback which meant I changed the default from true to false.

The run command on Ubuntu should be: ./geosparql-fuseki -rf "geosparql_test.rdf>xml" -i true
In the next release, it will be the simpler: ./geosparql-fuseki -rf "geosparql_test.rdf>xml" -i

I've updated the error message to hopefully make it clearer what is happening with lack of geometry literals.

The default SRS for GeoSPARQL is CRS84, which is lon/lat coordinate order. WGS84 is lat/lon. If using WGS84 then you shouldn't need to worry about the Apache SIS warnings. If using a different SRS or transforming SRS then they become relevant.
